import React, { useState } from 'react';
import { useDispatch } from 'react-redux';
import { useNavigate } from 'react-router-dom';
import { submitRFQ } from '../store/quoteSlice.js';
import { 
  Calculator, 
  Sparkles, 
  ArrowRight, 
  Check, 
  AlertCircle,
  TrendingDown,
  Building,
  Hammer
} from 'lucide-react';

const Estimator = () => {
  const [area, setArea] = useState('1000'); // Default 1000 sq ft
  const [floors, setFloors] = useState('1');
  const [buildType, setBuildType] = useState('Residential'); // Residential, Commercial, Industrial
  const [calculated, setCalculated] = useState(false);

  // Estimates results states
  const [cementBags, setCementBags] = useState(0);
  const [steelTons, setSteelTons] = useState(0);
  const [bricksCount, setBricksCount] = useState(0);
  const [sandTons, setSandTons] = useState(0);

  const dispatch = useDispatch();
  const navigate = useNavigate();
  const [rfqSuccess, setRfqSuccess] = useState(false);

  // Industry Standard Estimation Algorithms
  const calculateMaterials = (e) => {
    e.preventDefault();
    const sqFt = Number(area) * Number(floors);
    
    let multiplier = 1.0;
    if (buildType === 'Commercial') multiplier = 1.25;
    else if (buildType === 'Industrial') multiplier = 1.5;

    // Estimation Formulae (approximate industry standards):
    // Cement: ~0.4 bags per sq ft
    // Steel: ~0.004 tons (4kg) per sq ft
    // Bricks: ~20 pieces per sq ft
    // Sand: ~0.02 tons per sq ft
    setCementBags(Math.ceil(sqFt * 0.4 * multiplier));
    setSteelTons(Number((sqFt * 0.004 * multiplier).toFixed(2)));
    setBricksCount(Math.ceil(sqFt * 20 * multiplier));
    setSandTons(Math.ceil(sqFt * 0.02 * multiplier));
    
    setCalculated(true);
  };

  const convertEstimateToRFQ = async () => {
    if (!calculated) return;

    // Hardcode matching to product items seeded in database
    // Products:
    // Cement Category: UltraTech Premium Cement
    // Steel Category: TATA Tiscon TMT Steel Rebar FE 550D
    // Bricks Category: Red Clay Bricks (Class A)
    // Sand Category: River Sand (Coarse)
    
    try {
      const res = await fetch('http://localhost:5000/api/products');
      const data = await res.json();
      if (!res.ok) return;

      const catalog = data.data;

      // Locate product IDs
      const cementProduct = catalog.find(p => p.category === 'Cement') || {};
      const steelProduct = catalog.find(p => p.category === 'Steel') || {};
      const bricksProduct = catalog.find(p => p.category === 'Bricks') || {};
      const sandProduct = catalog.find(p => p.category === 'Sand') || {};

      const rfqItems = [
        { productId: cementProduct._id, quantity: cementBags, targetPrice: cementProduct.pricingTiers?.Builder || 380 },
        { productId: steelProduct._id, quantity: Math.ceil(steelTons) || 1, targetPrice: steelProduct.pricingTiers?.Builder || 58000 },
        { productId: bricksProduct._id, quantity: bricksCount, targetPrice: bricksProduct.pricingTiers?.Builder || 6 },
        { productId: sandProduct._id, quantity: Math.ceil(sandTons) || 1, targetPrice: sandProduct.pricingTiers?.Builder || 2800 },
      ].filter(item => item.productId !== undefined);

      const rfqAction = await dispatch(submitRFQ({
        items: rfqItems,
        remarks: `RFQ auto-generated by Material Estimator. Built: ${area} Sq.Ft, ${floors} Floors, ${buildType} Grade.`
      }));

      if (submitRFQ.fulfilled.match(rfqAction)) {
        setRfqSuccess(true);
        setTimeout(() => {
          setRfqSuccess(false);
          navigate('/quotes');
        }, 3000);
      }
    } catch (err) {
      alert('Error connecting to catalogue service');
    }
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      
      {/* Left Column: Dimensions Input Forms */}
      <div className="lg:col-span-1 glass-panel p-5 rounded-2xl border border-slate-800 h-fit space-y-4">
        <h3 className="font-bold text-sm text-slate-200 flex items-center gap-2 pb-3 border-b border-slate-800">
          <Calculator className="w-4 h-4 text-blue-500" />
          Estimation Calculator
        </h3>

        <form onSubmit={calculateMaterials} className="space-y-4">
          <div>
            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1.5">Total Floor Area (Sq. Ft.)</label>
            <input
              type="number"
              required
              value={area}
              onChange={(e) => setArea(e.target.value)}
              className="w-full glass-input px-3 py-2.5 rounded-xl text-xs"
              placeholder="e.g. 1500"
            />
          </div>

          <div>
            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1.5">Number of Floors</label>
            <input
              type="number"
              required
              min="1"
              value={floors}
              onChange={(e) => setFloors(e.target.value)}
              className="w-full glass-input px-3 py-2.5 rounded-xl text-xs"
              placeholder="e.g. 2"
            />
          </div>

          <div>
            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1.5">Construction Category</label>
            <div className="grid grid-cols-3 gap-2">
              {['Residential', 'Commercial', 'Industrial'].map(type => (
                <button
                  key={type}
                  type="button"
                  onClick={() => setBuildType(type)}
                  className={`py-2 rounded-xl text-[10px] font-bold border transition-all ${
                    buildType === type
                      ? 'bg-blue-600/10 border-blue-500/40 text-blue-400'
                      : 'bg-slate-950/40 border-slate-800 text-slate-400 hover:bg-slate-950/60'
                  }`}
                >
                  {type}
                </button>
              ))}
            </div>
          </div>

          <button
            type="submit"
            className="w-full py-2.5 bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold rounded-xl active:scale-95 transition-all shadow-lg shadow-blue-500/10 flex items-center justify-center gap-1.5"
          >
            <Hammer className="w-4 h-4" />
            Estimate Materials
          </button>
        </form>
      </div>

      {/* Right Column: Calculated Results & Convert to RFQ */}
      <div className="lg:col-span-2 space-y-6">
        
        {calculated ? (
          <div className="glass-panel p-6 rounded-2xl border border-slate-800 space-y-6">
            
            <div className="flex justify-between items-start pb-4 border-b border-slate-800">
              <div>
                <h3 className="text-base font-bold text-slate-200">Advisory Materials Breakdown</h3>
                <p className="text-xs text-slate-400 mt-1">Estimations calculated for a {Number(area) * Number(floors)} sq. ft. build footprint.</p>
              </div>
              <span className="px-2.5 py-1 bg-blue-500/10 text-blue-400 border border-blue-500/20 rounded-lg text-xs font-bold uppercase tracking-wider">
                {buildType} Grade
              </span>
            </div>

            {/* Results Grid Cards */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              
              {/* Cement */}
              <div className="p-4 bg-slate-950/40 border border-slate-850 rounded-2xl flex items-center gap-4">
                <div className="w-12 h-12 bg-blue-600/10 rounded-xl flex items-center justify-center border border-blue-500/20 text-blue-400 font-bold text-sm">OPC</div>
                <div>
                  <span className="text-[9px] font-bold text-slate-500 uppercase tracking-wider block">OPC Cement (53 Grade)</span>
                  <h4 className="text-xl font-extrabold text-slate-200 mt-0.5">{cementBags.toLocaleString()} Bags</h4>
                </div>
              </div>

              {/* Steel */}
              <div className="p-4 bg-slate-950/40 border border-slate-850 rounded-2xl flex items-center gap-4">
                <div className="w-12 h-12 bg-blue-600/10 rounded-xl flex items-center justify-center border border-blue-500/20 text-blue-400 font-bold text-sm">TMT</div>
                <div>
                  <span className="text-[9px] font-bold text-slate-500 uppercase tracking-wider block">TMT Reinforcement Steel</span>
                  <h4 className="text-xl font-extrabold text-slate-200 mt-0.5">{steelTons} Tons</h4>
                </div>
              </div>

              {/* Bricks */}
              <div className="p-4 bg-slate-950/40 border border-slate-850 rounded-2xl flex items-center gap-4">
                <div className="w-12 h-12 bg-blue-600/10 rounded-xl flex items-center justify-center border border-blue-500/20 text-blue-400 font-bold text-sm">BRK</div>
                <div>
                  <span className="text-[9px] font-bold text-slate-500 uppercase tracking-wider block">Red Clay/Fly Ash Bricks</span>
                  <h4 className="text-xl font-extrabold text-slate-200 mt-0.5">{bricksCount.toLocaleString()} Pcs</h4>
                </div>
              </div>

              {/* Sand */}
              <div className="p-4 bg-slate-950/40 border border-slate-850 rounded-2xl flex items-center gap-4">
                <div className="w-12 h-12 bg-blue-600/10 rounded-xl flex items-center justify-center border border-blue-500/20 text-blue-400 font-bold text-sm">SND</div>
                <div>
                  <span className="text-[9px] font-bold text-slate-500 uppercase tracking-wider block">Natural River Coarse Sand</span>
                  <h4 className="text-xl font-extrabold text-slate-200 mt-0.5">{sandTons.toLocaleString()} Tons</h4>
                </div>
              </div>

            </div>

            {/* Advisory block */}
            <div className="p-4 bg-slate-900/60 rounded-2xl border border-slate-800/80 text-[11px] text-slate-400 space-y-2">
              <span className="font-bold text-slate-300 flex items-center gap-1.5">
                <AlertCircle className="w-4 h-4 text-blue-500" />
                Algorithm Disclaimer
              </span>
              <p className="leading-relaxed">
                Calculations are structural approximations based on average dry volume mix ratios (1:2:4 cement/sand/aggregate) and structural detailing indexes (4 kg steel/sqft). Actual material demands are dependent on architectural design criteria, plaster specifications, and soil profiles.
              </p>
            </div>

            {/* Conversion CTA */}
            {rfqSuccess ? (
              <div className="bg-emerald-950/40 border border-emerald-500/30 text-emerald-300 p-4 rounded-xl flex items-center gap-2.5 text-xs animate-bounce justify-center">
                <Check className="w-4 h-4 text-emerald-400" />
                <span>Estimate converted successfully! Redirecting to Quotations portal...</span>
              </div>
            ) : (
              <button
                onClick={convertEstimateToRFQ}
                className="w-full py-3 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white text-xs font-bold rounded-xl shadow-lg hover:shadow-blue-500/25 active:scale-95 transition-all flex items-center justify-center gap-1.5"
              >
                <Sparkles className="w-4 h-4" />
                Convert Estimate to RFQ Quotation
                <ArrowRight className="w-4 h-4" />
              </button>
            )}

          </div>
        ) : (
          <div className="glass-panel p-10 rounded-2xl border border-slate-800 text-center text-slate-500 text-xs flex flex-col items-center justify-center py-40">
            <Calculator className="w-12 h-12 text-slate-700 mb-3" />
            <span className="font-semibold block text-slate-400 text-sm">Calculate Estimates</span>
            <span className="text-[11px] mt-1 text-slate-500">Provide construction size details in the left form to evaluate structural requirements.</span>
          </div>
        )}

      </div>

    </div>
  );
};

export default Estimator;
